### ISSUE TITLE
Support for Multiple Households

### ISSUE THREAD

**Issue by sbabcock23** [sbabcock23/pytryfi#19]
@ExodusOTH - opening an issue to support multiple households for pets and bases. You mentioned an issue with HA and the root of the issue can be found in the tryfi library. Opening for tracking purposes.

**Comment by sbabcock23** [comment]
@exodusOTH - can you please update your HA version of TryFi and let me know if this resolves the issue. I don't have the data to fully test but I believe I know what the issue is.

**Comment by 17kisern** [comment]
@sbabcock23 Just had my brother re-add me as an owner for his dog (for a temporary fix I had just removed my owner status of Scout), gave myself a fresh install of TryFi on Home Assistant with the new version (0.0.15) and it's working flawlessly now!

Thanks so much, amazing turnaround!

**Comment by ExodusOTH** [comment]
Ope, I was logged into the wrong GitHub account, can confirm it works perfectly now! @sbabcock23
