### ISSUE TITLE
Printing Dog's Location

### ISSUE THREAD

**Issue by Evan-Britton** [sbabcock23/pytryfi#23]
How do I grab the coordinates/location of my Dog using a function?

**Comment by sbabcock23** [comment]
You can grab the Long and Lats by doing the following:

- pryfi.pets[0].currLongitude
- pryfi.pets[0].currLatitude


If you are looking for the "friendly" location name which isn't always populated by TryFi would be:
- pryfi.pets[0].currPlaceName
- pryfi.pets[0].currPlaceAddress
