### ISSUE TITLE
Finding time of last collar update

### ISSUE THREAD

**Issue by Evan-Britton** [sbabcock23/pytryfi#24]
I figured out how to grab the time from which the data is accessed from the api using, tryfi.pets[0].lastUpdated, but this doesn't show the time the collar was updated, instead it shows the time you access the data from the api. How do I get the time of the last collar update?

Also could you attach a list of all the tryfi.pets[0] functions? Thanks!

**Comment by sbabcock23** [comment]
From what I remember, there was nothing in the data returned from TryFi that identifies the date/timestamp of the data being returned.

For a list of functions and properties for the pet, please look at the code found [here](https://github.com/sbabcock23/pytryfi/blob/master/pytryfi/fiPet.py).
